### ISSUE TITLE
MongoDB Error: Connection error

### ISSUE THREAD

**Issue by tesYolan** [tesYolan/Restforhead#1]
On new installation where mongodb isn't appropriately configured it would throw the following error:
```
connection error: { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }
```

**Comment by tesYolan** [comment]
This must be included in the README to actually site what needs to be done. Or must create the db. What are the standards to be followed? Would check and update the repository appropriately.

**Comment by tesYolan** [comment]
Since it's going to be depend on docker? May be pulling a mongodb image and then building the image on top of that.
