### ISSUE TITLE
Starting the container failed

### ISSUE THREAD

**Issue by tesYolan** [tesYolan/Restforhead#19]
[0] error: starting the container failed
[0] error: get's to error
[0] error:  Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint instance_name (38fda25e598ac426aa8d8784a4c5cc0074136fd1c4eae5caa8f49db969508c7e): Error starting userland proxy: listen tcp 0.0.0.0:50834: bind: address already in use 
[0]     at /home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:251:17
[0]     at getCause (/home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:281:7)
[0]     at Modem.buildPayload (/home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:250:5)
[0]     at IncomingMessage.<anonymous> (/home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:226:14)
[0]     at emitNone (events.js:91:20)
[0]     at IncomingMessage.emit (events.js:185:7)
[0]     at endReadableNT (_stream_readable.js:974:12)
[0]     at _combinedTickCallback (internal/process/next_tick.js:80:11)
[0]     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by tesYolan** [comment]
This shouldn't have been the case as py-app/misc.py should have created ports that are free.
