### ISSUE TITLE
RTSP Server connection error

### ISSUE THREAD

**Issue by tesYolan** [tesYolan/Restforhead#3]
```
RTSP server started rtsp://192.168.1.48:5000
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 192.168.1.48:3443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

```

**Comment by tesYolan** [comment]
This error is indicative of the status of the port where it's trying to listen to. The best resolution currently is to setting https://github.com/tesYolan/Restforhead/blob/master/config/config.js#L19 to appropriate value in the system.

**Comment by tesYolan** [comment]
The error is primary the IP:PORT values must be valid for the current system to act as a server. In this particular case, the IP is not valid and hence the error.
