### ISSUE TITLE
_handleProtooPeer() failed

### ISSUE THREAD

**Issue by tesYolan** [tesYolan/Restforhead#31]
When launching the application it throws the following error and doesn't response afterwards. 
```
[0] error: _handleProtooPeer() failed: 
[0] error: stack:
[0] Error
[0]     at Peer._handleResponse (/home/tesfa/projects/Restforhead/node_modules/protoo-server/lib/Peer.js:177:16)
[0]     at WebSocketTransport._transport.on (/home/tesfa/projects/Restforhead/node_modules/protoo-server/lib/Peer.js:152:10)
[0]     at emitOne (events.js:96:13)
[0]     at WebSocketTransport.emit (events.js:188:7)
[0]     at WebSocketConnection._connection.on (/home/tesfa/projects/Restforhead/node_modules/protoo-server/lib/transports/WebSocketTransport.js:118:9)
[0]     at emitOne (events.js:96:13)
[0]     at WebSocketConnection.emit (events.js:188:7)
[0]     at WebSocketConnection.processFrame (/home/tesfa/projects/Restforhead/node_modules/websocket/lib/WebSocketConnection.js:552:26)
[0]     at /home/tesfa/projects/Restforhead/node_modules/websocket/lib/WebSocketConnection.js:321:40
[0]     at _combinedTickCallback (internal/process/next_tick.js:73:7)
[0]     at process._tickCallback (internal/process/next_tick.js:104:9)
```
It crashes the backend as creating new instances doesn't do anything afterwards. Possibly because nodemon doesn't doesn't restarts the application. Use a better tool for that.

**Comment by tesYolan** [comment]
Similar problem related to timeout: 
```
[0] error: _handleProtooPeer() failed: request timeout
[0] error: stack:
[0] Error: request timeout
[0]     at Timeout.handler.timer.setTimeout [as _onTimeout] (/home/tesfa/projects/Restforhead/node_modules/protoo-server/lib/Peer.js:92:16)
[0]     at ontimeout (timers.js:380:14)
[0]     at tryOnTimeout (timers.js:244:5)
[0]     at Timer.listOnTimeout (timers.js:214:5)
```
