### ISSUE TITLE
Mongodb Connection Error

### ISSUE THREAD

**Issue by tesYolan** [tesYolan/Restforhead#4]
When starting the application i face the following error: 
```
connection error: { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }

```

**Comment by tesYolan** [comment]
The mongod service may not be running: run the following code
```
sudo service mongod start

```

**Comment by tesYolan** [comment]
This needs to be included in the ```npm start``` to system.

**Comment by tesYolan** [comment]
Duplicate of #1. Closed.
