### ISSUE TITLE
Error when running docker 

### ISSUE THREAD

**Issue by kkalkidan** [tesYolan/Restforhead#42]
Hi Tesfa , 

I encountered this error, while following the easy installation steps, when running ```./build.sh ```. 
I am using  mac : 
```
  System Version:	macOS 10.13.4 (17E199)
  Kernel Version:	Darwin 17.5.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
```
 Docker Version :  `Docker version 18.03.1-ce, build 9ee9f40`

```
Downloading/unpacking gevent>=1.0 (from zerorpc)
  Running setup.py (path:/tmp/pip-build-0DgKKX/gevent/setup.py) egg_info for package gevent
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-0DgKKX/gevent/setup.py", line 417, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "/tmp/pip-build-0DgKKX/gevent/setup.py", line 401, in run_setup
        "signal_os_incompat = gevent.monkey:_subscribe_signal_os",
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 603, in resolve
        requirements = list(requirements)[::-1]
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements
        "version spec")
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2697, in scan_list
        raise ValueError(msg, line, "at", line[p:])
    ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-0DgKKX/gevent/setup.py", line 417, in <module>

    run_setup(EXT_MODULES, run_make=_BUILDING)

  File "/tmp/pip-build-0DgKKX/gevent/setup.py", line 401, in run_setup

    "signal_os_incompat = gevent.monkey:_subscribe_signal_os",

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs

    replace_conflicting=True,

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 603, in resolve

    requirements = list(requirements)[::-1]

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements

    "version spec")

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2697, in scan_list

    raise ValueError(msg, line, "at", line[p:])

ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-0DgKKX/gevent
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install pyzmq zerorpc' returned a non-zero code: 1
```

**Comment by tesYolan** [comment]
I see, let's come back to you.

**Comment by tesYolan** [comment]
Removing zerorpc from https://github.com/tesYolan/Restforhead/blob/master/Dockerfile#L7 seems to fix the issue temporarily. Though a better solution would be needed.
