### ISSUE TITLE
Lost remote error 

### ISSUE THREAD

**Issue by kkalkidan** [tesYolan/Restforhead#44]
Hello Tesfa,
 When connecting to `Local: https://localhost:3002`, it stays connected for the first 10 secs and then crashes. 
  
```
node_1     | [0] error:  HeartbeatError: Lost remote after 10000ms
node_1     | [0]     at Object.createErrorResponse (/home/node/app/node_modules/zerorpc/lib/util.js:53:10)
node_1     | [0]     at ClientChannel.<anonymous> (/home/node/app/node_modules/zerorpc/lib/client.js:163:26)
node_1     | [0]     at emitOne (events.js:116:13)
node_1     | [0]     at ClientChannel.emit (events.js:211:7)
node_1     | [0]     at Timeout._onTimeout (/home/node/app/node_modules/zerorpc/lib/channel.js:198:18)
node_1     | [0]     at ontimeout (timers.js:498:11)
node_1     | [0]     at tryOnTimeout (timers.js:323:5)
node_1     | [0]     at Timer.listOnTimeout (timers.js:290:5)
node_1     | [0] info: Producer "close" event [originator:local]
node_1     | [0] info: Producer "close" event [originator:local]
node_1     | [0] info: Transport "close" event [originator:local]
node_1     | [0] /home/node/app/models/Room.js:498
node_1     | [0]         that._mediaRoom.createRtpStreamer(producer, {'remoteIP': config.mediasoup.rtpConfig.audio.remoteIP, 'remotePort': port[0]}).then((rtpStreamer) => {
node_1     | [0]                                                                                                                               ^
node_1     | [0] 
node_1     | [0] TypeError: Cannot read property '0' of undefined
node_1     | [0]     at DisplayManager.getFreePort (/home/node/app/models/Room.js:498:127)
node_1     | [0]     at callbackErrorWrapper (/home/node/app/node_modules/zerorpc/lib/client.js:105:13)
node_1     | [0]     at ClientChannel.<anonymous> (/home/node/app/node_modules/zerorpc/lib/client.js:164:9)
node_1     | [0]     at emitOne (events.js:116:13)
node_1     | [0]     at ClientChannel.emit (events.js:211:7)
node_1     | [0]     at Timeout._onTimeout (/home/node/app/node_modules/zerorpc/lib/channel.js:198:18)
node_1     | [0]     at ontimeout (timers.js:498:11)
node_1     | [0]     at tryOnTimeout (timers.js:323:5)
node_1     | [0]     at Timer.listOnTimeout (timers.js:290:5)
```

**Comment by tesYolan** [comment]
Ah, This seems to point back to the zerorpc code that we aren't running currently. 

To illustrate: from https://github.com/tesYolan/Restforhead/blob/master/models/Room.js#L476

```
      DisplayManager.getFreePort('dummy', (error, port, more) => {
        if (error) logger.error(error)
        that._mediaRoom.createRtpStreamer(producer, {'remoteIP': config.mediasoup.rtpConfig.video.remoteIP, 'remotePort': port[0]}).then((rtpStreamer) => {
```
Since there isn't zerorpc library to heed the call, this call dies. 

Thanks for the patience while I work to resolve the issue. I guess you have to wait a bit more before I can come back a way to resolve the past couple of issues.
