### ISSUE TITLE
Environ raising key error

### ISSUE THREAD

**Issue by kkalkidan** [tesYolan/Restforhead#46]
Hi Tesfa, 

 I get this error when I try running `npm test`.

````

concurrently --kill-others -s first "mocha" "python py-app/misc.py"

[1] Traceback (most recent call last):
[1]   File "py-app/misc.py", line 41, in <module>
[1]     rpc_port = "tcp://" + str(os.environ['RPC_IP'])+":"+str(os.environ['RPC_PORT'])
[1]   File "/Users/kalkidanfekadu/anaconda2/lib/python2.7/UserDict.py", line 40, in __getitem__
[1]     raise KeyError(key)
[1] KeyError: 'RPC_IP'
[1] python py-app/misc.py exited with code 1
--> Sending SIGTERM to other processes..
[0] mocha exited with code null

```

**Comment by kkalkidan** [comment]
Sorry my bad. I didn't run it in the container. Sorry for that.
