### ISSUE TITLE
KeyError: 'FFMPEG'

### ISSUE THREAD

**Issue by tesYolan** [tesYolan/Restforhead#5]
When i start up the script the following error pops up
```
Traceback (most recent call last):
  File "misc.py", line 83, in <module>
    s = zerorpc.Server(Misc())
  File "misc.py", line 18, in __init__
    self.FFMPEG = os.environ['FFMPEG']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'FFMPEG'

```

**Comment by tesYolan** [comment]
This issue starts up when we don't know what the FFMPEG executable to use. There needs to be mechanism to actually indicate have a fail safe back option to go for the system. 

In addition there needs to be indication in the documentation whether to install ffmpeg.
