### ISSUE TITLE
Container already stopped

### ISSUE THREAD

**Issue by tesYolan** [tesYolan/Restforhead#7]
When user deletes the following error comes up repeatedly:
```
[0] Deleting All Instances
[0] name to stop and delete instance_name
[0] get's to error
[0] { Error: (HTTP code 304) container already stopped -  
[0]     at /home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:251:17
[0]     at getCause (/home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:281:7)
[0]     at Modem.buildPayload (/home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:250:5)
[0]     at IncomingMessage.<anonymous> (/home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:226:14)
[0]     at emitNone (events.js:91:20)
[0]     at IncomingMessage.emit (events.js:185:7)
[0]     at endReadableNT (_stream_readable.js:974:12)
[0]     at _combinedTickCallback (internal/process/next_tick.js:80:11)
[0]     at process._tickCallback (internal/process/next_tick.js:104:9)
[0]   reason: 'container already stopped',
[0]   statusCode: 304,
[0]   json: '' }

```

This causes the system to not delete the container. Fixing the code to delete and continue to delete if it's still stopped.

**Comment by tesYolan** [comment]
I assumed error if the docker stop returns error. I should jump to correcting that state (if that's the subsequent steps need) or continue with this state without changing the state if the subsequent steps can operate on stopped instance.
