### ISSUE TITLE
MongoError: E11000 duplicate key error collection: instances.instances index: name_1 dup key: { : "instance_name" 

### ISSUE THREAD

**Issue by tesYolan** [tesYolan/Restforhead#9]
```
[0] { MongoError: E11000 duplicate key error collection: instances.instances index: name_1 dup key: { : "instance_name" }
[0]     at Function.MongoError.create (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb-core/lib/error.js:31:11)
[0]     at toError (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb/lib/utils.js:139:22)
[0]     at /home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb/lib/collection.js:669:23
[0]     at handleCallback (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb/lib/utils.js:120:56)
[0]     at /home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb/lib/bulk/unordered.js:465:9
[0]     at handleCallback (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb/lib/utils.js:120:56)
[0]     at resultHandler (/home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb/lib/bulk/unordered.js:413:5)
[0]     at /home/tesfa/projects/talktohead/Restforhead/node_modules/mongodb-core/lib/connection/pool.js:469:18
[0]     at _combinedTickCallback (internal/process/next_tick.js:73:7)
[0]     at process._tickCallback (internal/process/next_tick.js:104:9)
[0]   name: 'MongoError',
[0]   message: 'E11000 duplicate key error collection: instances.instances index: name_1 dup key: { : "instance_name" }',
[0]   driver: true,
[0]   code: 11000,
[0]   index: 0,
[0]   errmsg: 'E11000 duplicate key error collection: instances.instances index: name_1 dup key: { : "instance_name" }',
[0]   getOperation: [Function],
[0]   toJSON: [Function],
[0]   toString: [Function] }
[0] 354368729
[0] get's to error
```

And related to this 
 ```
{ Error: (HTTP code 409) unexpected - Conflict. The container name "/instance_name" is already in use by container "c36a56ab1e31e658b69268df04627858ff1e8b307b387e2a426d66c979e68023". You have to remove (or rename) that container to be able to reuse that name. 
[0]     at /home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:251:17
[0]     at getCause (/home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:281:7)
[0]     at Modem.buildPayload (/home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:250:5)
[0]     at IncomingMessage.<anonymous> (/home/tesfa/projects/talktohead/Restforhead/node_modules/docker-modem/lib/modem.js:226:14)
[0]     at emitNone (events.js:91:20)
[0]     at IncomingMessage.emit (events.js:185:7)
[0]     at endReadableNT (_stream_readable.js:974:12)
[0]     at _combinedTickCallback (internal/process/next_tick.js:80:11)
[0]     at process._tickCallback (internal/process/next_tick.js:104:9)
[0]   reason: undefined,
[0]   statusCode: 409,
[0]   json: { message: 'Conflict. The container name "/instance_name" is already in use by container "c36a56ab1e31e658b69268df04627858ff1e8b307b387e2a426d66c979e68023". You have to remove (or rename) that container to be able to reuse that name.' } }

```

This is when there invalid state in mongodb.

**Comment by tesYolan** [comment]
Check for valid values when users give instance_names in this app.

**Comment by kkalkidan** [comment]
Hi Tesfa,

For this issue,  we might use flash messaging to handle it.  Below I have created a similar example to explain how it can be used.

```
var session = require('express-session')   // req.flash requires session

const flash = require('connect-flash')

      app.use(session({cookie:{ maxAge: 60000},   
                        store: sessionStore,
                        secret: 'secret',
                        resave: true,
                        saveUninitialized: true}))

      app.use(flash())

=================================================================

// Saving instance to the database 
          new_instance.save((err, instance) => {
         
            if(err) {  // in case of dulicate error
              console.log(err)
              req.flash('error', `${new_instance_name} already exists`)
              res.redirect('/createInstancePage')
              return;
          } else console.log(`saving ${new_instance}`)
            res.redirect('/createInstancePage')
     
     
```

In the page we redirect to (`createInstancePage` ), we write the `req.flash('error')` to the response. 
```
router.route('/createInstancePage')
  .get((req, res, next) => {
    res.writeHead(200, {'Content-Type' : 'application/json'})
    res.write(`${req.flash('error')}`)
    Instances.find((err, instance) => {
      if(err) console.log(err)
      res.write(JSON.stringify(instance))
      res.end()
    })

```
`req.flash('error')` has a value only when there is a duplicate error ( when `/createInstancePage` is a redirected page from inside the condition that handles duplicate error ).
